---
apiVersion: 1
datasources:
  # Prometheus data source
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus_uid
    url: http://localhost:9090
    isDefault: true
    editable: true