{
 "title": "Host Resources Usage",
 "description": "Collect information about host resource usage.",
 "time": { "from": "2024-11-19T12:59:13.572Z", "to": "2024-11-19T14:48:05.137Z" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"localhost:9100\"} - node_memory_MemFree_bytes{instance=\"localhost:9100\"} - node_memory_Cached_bytes{instance=\"localhost:9100\"} - node_memory_Buffers_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{instance=\"localhost:9100\", mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 6, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"localhost:9100\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"localhost:9100\"}[5m])",
     "legendFormat": "{{device}} transimt"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"localhost:9100\", device!~\"/dev/loop.*\", device!~\"tmpfs | nsfs\", device!=\"gvfsd_fuse\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"localhost:9100\", device=\"/dev/root\"} ",
     "legendFormat": "{{device}} free"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"localhost:9100\", device=\"/dev/root\"} - node_filesystem_avail_bytes{instance=\"localhost:9100\", device=\"/dev/root\"}",
     "legendFormat": "{{device}} used"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"localhost:9100\", device!~\"/dev/loop.*\", device!~\"tmpfs | nsfs\", device!=\"gvfsd-fuse\"} - node_filesystem_avail_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}